### ISSUE TITLE
5: S3 - Host static build of dfrm_fe 

### ISSUE THREAD

**Issue by tylerstright** [NPTfisheries/dfrm_website#1]
I made this work: https://www.linkedin.com/pulse/deploying-your-angular-app-aws-s3-step-by-step-guide-cengkuru-michael-wnsrf/

TO DO:  Update the production build to target the appropriate backend API, once established. (dfrm_fe/environments/environment.ts).

Steps:
1. Establish an AWS account for the website, build user as needed for appropriate permissions (IAM?).
3. Start S3 bucket for site.
4. Follow steps on link above.

Hint:  The bucket / root is the same as the dist/dfrm_fe folder - the files/folders inside the build dist/dfrm_fe folder should be copied into the S3 bucket root.

**Comment by ryankinzer** [comment]
static front end is hosted in S3 bucket. May need to revisit security/access of buckets.
